# Generated by Django 5.2.5 on 2025-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('wholesaler', 'Wholesaler'), ('organization', 'Organization')], default='organization', max_length=20),
        ),
    ]
